### ISSUE TITLE
Windows console history via F7 does not work in terminal mode

### ISSUE THREAD

**Issue by mariusgreuel** [avrdudes/avrdude#1097] opened 2022-09-06 15:17 UTC
When I use the console shortcut `F7` in terminal mode to bring up the history, the history shows, but when selecting an item, it seems only the first character is being read, and not the entire command. Other editing commands such as cursor up/down, F3, etc. seem to work.

**Comment by mariusgreuel** [comment] 2022-09-06 15:32
OK, something totally weird is happening upon F7: Using the avrdude code with

```
char input[256] = { 0 };
char* returns = fgets(input, sizeof(input), stdin);
```

and selecting a string of '123' from the history gives me a input buffer with

  | Name | Value | Type
-- | -- | -- | --
  | [0] | 49 '1' | char
  | [1] | 0 '\0' | char
  | [2] | 0 '\0' | char
  | [3] | 0 '\0' | char
  | [4] | 50 '2' | char
  | [5] | 0 '\0' | char
  | [6] | 0 '\0' | char
  | [7] | 0 '\0' | char
  | [8] | 51 '3' | char
  | [9] | 0 '\0' | char
  | [10] | 10 '\n' | char
  | [11] | 0 '\0' | char

**Comment by mariusgreuel** [comment] 2022-09-06 15:59
Hm, did some playing and it seems `ReadFile` and `ReadConsoleA` is broken on Windows 10. When I use the Unicode API `ReadConsoleW`, `F7` works.

<details>
<summary>The glory details...</summary>

```c
#include <stdio.h>
#include <string.h>
#include <malloc.h>
#include <windows.h>

#define USE_UNICODE 1

char* terminal_get_input(const char* prompt)
{
    printf("%s", prompt);
#if USE_UNICODE
    DWORD dwCharsRead = 0;
    WCHAR wcBuffer[256] = { 0 };
    if (ReadConsoleW(
        GetStdHandle(STD_INPUT_HANDLE),
        wcBuffer,
        ARRAYSIZE(wcBuffer),
        &dwCharsRead,
        NULL))
    {
        CHAR acBuffer[256] = { 0 };
        int nChars = WideCharToMultiByte(
            GetConsoleCP(),
            0,
            wcBuffer,
            dwCharsRead,
            acBuffer,
            ARRAYSIZE(acBuffer) - 1,
            NULL,
            NULL);
        if (nChars > 0)
        {
            acBuffer[nChars] = 0;
            return _strdup(acBuffer);
        }
    }

    return NULL;
#else
    DWORD dwCharsRead = 0;
    CHAR acBuffer[256] = { 0 };
    if (ReadConsoleA(
        GetStdHandle(STD_INPUT_HANDLE),
        acBuffer,
        ARRAYSIZE(acBuffer) - 1,
        &dwCharsRead,
        NULL))
    {
        if (dwCharsRead > 0)
        {
            acBuffer[dwCharsRead] = 0;
            return _strdup(acBuffer);
        }
    }

    return NULL;
#endif

#if OLD_IMPLEMENTATION
    char input[256] = { 0 };
    char* returns = fgets(input, sizeof(input), stdin);
    if (returns)
    {
        return _strdup(input);
    }
    else
    {
        return NULL;
    }
#endif
}

int main()
{
    while (1)
    {
        char* buffer = terminal_get_input("avrdude> ");
        printf("Got: '%s'\n", buffer);
        free(buffer);
    }
}
```
</details>

**Comment by mcuee** [comment] 2022-09-07 01:37
Yes I can reproduce on my Windows 10 Laptop. After selecting the option, only the first character is read.

```
avrdude> dump eeprom

>>> d
Usage: d <memory> <addr> <len>
       d <memory> <addr> ...
       d <memory> <addr>
       d <memory> ...
       d <memory>

```

![F7_avrdude_cmd](https://user-images.githubusercontent.com/1294740/188769441-bdea9aff-f68b-47a5-8e3f-ed860cda235c.JPG)

**Comment by mcuee** [comment] 2022-12-31 07:39
I think this can be a low priority. If we can get #1186 fixed, then I believe it does not really matter much any more.
* #1186

**Comment by mcuee** [comment] 2023-01-04 09:17
#1264 seems to be able to fix this issue.
* #1264

**Comment by stefanrueger** [comment] 2023-01-04 18:09
| something totally weird is happening upon F7

I suspect this is '123' in 32-bit unicode, not? Hence your success when using the Unicode API ReadConsoleW...

**Comment by mariusgreuel** [comment] 2023-01-04 19:03
> I suspect this is '123' in 32-bit unicode, not?

No, it's random. Sometimes the first few characters are returned (i.e. as ANSI bytes), and the rest is missing (which may look like UTF32?).

I tried reading from the Unicode stream std::wcin, but it appears it is still using ReadFile and not ReadConsoleW, so this did not work. Anyway, I will not spend more time on this, as converting a stream into a line is not trivial. I submitted a bug report to Microsoft, lets see if anybody cares.

<https://aka.ms/AAj3zlf>

**Comment by mcuee** [comment] 2023-01-05 01:23
PR #1264 seems to sort out #1097 as well.
F7 will bring in the history. It is interesting that it may have the history of previous runs.

![Capture1](https://user-images.githubusercontent.com/1294740/210507242-37db07ae-0db1-4c49-a982-a278772c6c5c.JPG)
![Capture2](https://user-images.githubusercontent.com/1294740/210507276-931c6855-bafc-4179-b571-853cae1b2958.JPG)

Once I click RETURN, it will run.

**Comment by mcuee** [comment] 2023-03-28 03:39
@mariusgreuel 

Can we close this issue? At least the MSVC version now works with F7.

**Comment by mcuee** [comment] 2023-06-20 12:16
I will close this issue now since it works with MSVC version.

**Closed by mcuee** 2023-06-20 12:16 UTC
Labels: bug
