### ISSUE TITLE
snap / pickit4 in JTAG mode?

### ISSUE THREAD

**Issue by bonidydy** [avrdudes/avrdude#1123] opened 2022-10-11 19:17 UTC
Could it be possible to program with snap / pickit4 over JTAG?

**Comment by mcuee** [comment] 2022-10-11 23:53
Duplicate of #1052.
* https://github.com/avrdudes/avrdude/issues/1052

**Comment by mcuee** [comment] 2022-10-11 23:54
Please have further discussion in #1052.

**Closed by mcuee** 2022-10-11 23:53 UTC
Labels: duplicate
