### ISSUE TITLE
[bug #53279] Permission denied accessing /sys/class/gpio/gpioX/direction would leave pin exported

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avrdude#472] opened 2021-12-11 00:35 UTC
Michael Cain <loud.mouth.braggart@gmail.com>
Sat 03 Mar 2018 10:10:16 PM UTC
Programmer hardware: linuxgpio
Device type: RaspberryPi

When using a Raspberry Pi to program an atmega2560 using linuxgpio and you do not have the permission to access /sys/class/gpio/gpioX/direction it would leave the gpio pin exported.  The only way to unexport the pin would be to reboot the Rasbperry Pi.

The problem lies in the function linuxgpio_open, change line 280 from:
if (r < 0)
return r;

TO:
if (r < 0) {
linuxgpio_unexport(pin);
return r;
}

This issue was migrated from https://savannah.nongnu.org/bugs/?53279

**Comment by mcuee** [comment] 2022-06-06 13:18
Yes this is indeed similar to #917 and #372.
* #917 
* #372

**Comment by mcuee** [comment] 2022-07-10 14:06
I will mark this as duplicate of #386 and the fix is in #917.

**Closed by mcuee** 2022-07-10 14:06 UTC
Labels: bug, duplicate
