### ISSUE TITLE
JTAG2UPDI: avrdude error: cannot find programmer id jtag2updi

### ISSUE THREAD

**Issue by androot2** [avrdudes/avrdude#1845] opened 2024-07-27 10:00 UTC
In previous version 2.13 works well.

**Comment by MCUdude** [comment] 2024-07-27 10:07
There is no such thing as 2.13. Please provide more information, and an Avrdude output log.

**Comment by mcuee** [comment] 2024-07-27 10:28
> In previous version 2.13 works well.

Are you using Arduino IDE? Even then there is no version 2.13. 

And if you are using Arduino IDE, it comes with an old version of avrdude. You should use avrdude release from this repo.

**Comment by stefanrueger** [comment] 2024-08-01 17:29
Closing this as we cannot reproduce the reported problem and don't have more information for further investigations. @androot2 you can reopen any time. Here guidelines [how to report issues](https://github.com/avrdudes/avrdude/wiki/FAQ#how-to-report-an-issue-to-avrdude-project)

**Closed by stefanrueger** 2024-08-01 17:29 UTC
Labels: question
